# Generated by Django 3.0 on 2019-12-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0002_auto_20191206_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a0', models.FloatField()),
                ('a1', models.FloatField()),
                ('a2', models.FloatField()),
            ],
        ),
    ]
